# Generated by Django 5.0.6 on 2024-06-06 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('piso', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('activa', models.BooleanField(default=False)),
                ('ultimoLogin', models.DateTimeField(auto_now=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.agencia')),
            ],
        ),
    ]
