# Generated by Django 5.1.4 on 2025-01-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='switch',
            name='piso',
            field=models.PositiveIntegerField(),
        ),
    ]
