# Generated by Django 5.1.4 on 2025-01-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_alter_switch_ip_alter_switch_piso'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='passwordssh',
            field=models.CharField(default='cisco123', max_length=10),
        ),
        migrations.AddField(
            model_name='switch',
            name='userssh',
            field=models.CharField(default='admin', max_length=30),
        ),
    ]
